### ISSUE TITLE
Update GAIN to output the set of negatives for each GO term

### ISSUE THREAD

**Issue by jlaw9** [jlaw9/fungcat-function-prediction#4]
More details outlined in the [group google doc](https://docs.google.com/document/d/1syHAZ3od1SZm0tCJyeFru4tHutr002t-5FAgG1h0SLY/edit#heading=h.6skhmo3uawx7)

**Comment by jlaw9** [comment]
Probably easier to use another tool such as go_expansion https://github.com/IGACAT/GOManipulation

**Comment by tmmurali** [comment]
OK with me if we add functionality for negatives to go_expansion. There are
different strategies for assigning negatives for a specific GO term, so
there should be a way to invoke each such approach. I can think of three:

(i) Randomly select a set of genes.
(ii) Use all positives for non-ancestral GO terms.
(iii) Use all positives for sibling GO terms.

**Comment by tmmurali** [comment]
@jlaw9 any progress on this issue? See Gaurav's email message to the FunGCAT mailing list asking for this list of negatives.

**Comment by jlaw9** [comment]
@tmmurali not yet. I'll start working on it now.

**Comment by jlaw9** [comment]
@tmmurali can you elaborate on assigning negatives using "sibling GO terms?"

For ii, I assume you're referring to the method we use in GAIN of defining negatives, which is the set of genes not annotated to the function, nor a descendant or an ancestor function, but is also annotated with some other function

**Comment by jlaw9** [comment]
this issue is now handled on the igacat repo https://github.com/IGACAT/go_term_prediction_examples/issues/4
